// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

declare global {
  interface Window {
    __ENV__?: { SUPABASE_URL?: string; SUPABASE_PUBLISHABLE_KEY?: string };
  }
}

function createSupabaseClient() {
  // Priority:
  //  1. VITE_* build-time vars (baked in by Vite when build args are provided)
  //  2. window.__ENV__  – injected by the SSR server from process.env at request time
  //  3. process.env.*   – server-side (SSR) direct access
  const isServer = typeof window === "undefined";
  const runtimeEnv = isServer ? undefined : window.__ENV__;
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    runtimeEnv?.SUPABASE_URL ||
    (isServer ? process.env.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimeEnv?.SUPABASE_PUBLISHABLE_KEY ||
    (isServer ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
